### PR TITLE
Update workflow description and illustration

### PR DESCRIPTION
**Pull request by hyu**
I designed a new workflow diagram that is more visual, and IMO easier to understand at a glance. It was an interesting exercise, because I found it tempting to get overly detailed about the precise tools and deliverables. I hope that what I have here is at the right level. It's not really meant to be comprehensive. But one of my main goals was to show the ideal cycle where everything we deliver informs what we deliver next.

workflow

### CODE REVIEW

**Comment by nicks** [comment]
6313065931_b64e1dab20_o

**Comment by jazzdan** [comment]
https://i.chzbgr.com/full/7375383296/h21B62E4E/wow-this-is-so-cool

**Comment by maiamcc** [comment]
🤩🤩🤩

**Comment by victorwuky** [comment]
Thanks @hyu . This is great. Feel free to merge. I don't have any interesting cat pictures.

**Pull request merged**
